### ISSUE TITLE
Option to ignore the error instead of correcting it

### ISSUE THREAD

**Issue by andreyorst** [emacs-languagetool/flymake-languagetool#11]
In other implementations of language-tool packages for Emacs, it is possible to clear the highlighting, or dismiss the error entirely. For instance, [this package](https://github.com/PillFall/languagetool.el) has a menu entry for that:

![image](https://user-images.githubusercontent.com/19470159/199306506-eb319e18-28a8-44f1-bccc-a8b7b5ad1be4.png)

Pressing <kbd>C-i</kbd> on the error will make langtool ignore it for the end of the session.

[This package](https://github.com/mhayashi1120/Emacs-langtool) also has a similar feature, but assigns it to the <kbd>i</kbd> key in the menu.

With flymake-languagetool's `flymake-languagetool-correct-at-point` interface using completing read it is impossible to ignore some false positives that occur often in markup-based buffers, like Org mode.

E.g. here:

![image](https://user-images.githubusercontent.com/19470159/199308825-613fcb45-197d-4860-b02c-a2087d21baca.png)

I can't make a correction and I can silence this particular case, which makes it harder to keep track of whether there are new errors

**Comment by tpeacock19** [comment]
This is a good idea. Currently, you can add rules to `flymake-languagetool-disabled-rules`. But this would require users know the rules beforehand and also apply to the entire buffer. In this specific instance you would need to add `DOUBLE_PUNCTUATION`.

I'll look into adding options to ignore the specific error at point and/or ignoring the rule for the entire buffer. It will take me a bit to get to it, but when I do it'd be great to get feedback.

**Comment by tpeacock19** [comment]
I've added an option to ignore a Rule or Category. It can only be temporary/buffer-local but I think it should work. Let me know if this works for you.

**Comment by tpeacock19** [comment]
Closing this but still interested in your feedback if you have any.
