### ISSUE TITLE
EoL diagnostics not working properly

### ISSUE THREAD

**Issue by fabcontigiani** [emacs-languagetool/flymake-languagetool#19]
The ability to show end-of-line diagnostics is a relatively new feature introduced in `flymake` [last year](https://git.savannah.gnu.org/cgit/emacs.git/commit/lisp/progmodes/flymake.el?id=d45f450cff757ed520a7ee36c632ab62387c7bc9). 

When enabling this feature along with `flymake-languagetool`, the diagnostics seem to be inserted into the text buffer instead of being displayed as in other use cases. I don't know if this is a limitation of `text-mode` or something unrelated to this package.

**Original buffer:**
![image](https://github.com/emacs-languagetool/flymake-languagetool/assets/25231400/5c3428f0-31b9-48e3-a48f-4d531ca0e13f)

**After `M-x flymake-mode`:**
![image](https://github.com/emacs-languagetool/flymake-languagetool/assets/25231400/46913e94-801f-49ae-ace4-431b8984cd5e)

**Expected behavior:**
![image](https://github.com/emacs-languagetool/flymake-languagetool/assets/25231400/cb8eadb7-f7a4-46f8-a16d-079ee6472a2a)

Emacs version: 29.2
flymake version: 1.3.7
LanguageTool version: 6.3

Relevant configuration used in screenshots:
```elisp 
;;; init.el
(use-package flymake
  :hook prog-mode
  :custom
  (flymake-show-diagnostics-at-end-of-line 'short)
  (flymake-no-changes-timeout 1.5))

(use-package flymake-languagetool
  :hook ((text-mode latex-mode org-mode markdown-mode) . flymake-languagetool-load)
  :custom
  (flymake-languagetool-server-jar "/home/fab/LanguageTool-6.3/languagetool-server.jar"))
```

**Comment by tpeacock19** [comment]
Thanks for the note, I actually was not aware of this feature. It
should be fixed with the most recent commit
8c7f97e5dc831bfefe847a19ef034da5a8d41244. I'm planning to implement
some customizations surrounding the levels, but currently they all
show up as "warnings".
