### ISSUE TITLE
Allow customizing command to start languagetool server

### ISSUE THREAD

**Issue by ivan-pop** [emacs-languagetool/flymake-languagetool#6]
Some linux distributions provide shell scripts to launch languagetool server so that users can launch it from CLI without knowing exact path to languagetool jar file. It would be nice to be able to set command to run that script instead of searching for location of jar file.

**Comment by tpeacock19** [comment]
Can you give more information on the distro you that are using and what this command is?

**Comment by ivan-pop** [comment]
I quickly looked at [languagetool package in archlinux](https://github.com/archlinux/svntogit-community/tree/packages/languagetool/trunk) and it seems to provide similar script, though it just wraps every languagetool command in single script, unlike on NixOS different scripts for different commands.

**Comment by tpeacock19** [comment]
Okay, I do think it is a good idea to provide a server command. Additionally we should probably define the java executable using `(executable-find "java")`. I'll leave some comments on your PR.

**Comment by ivan-pop** [comment]
Predicate in `flymake-languagetool--start` should be changed to 

```elisp
(when (or flymake-languagetool-server-command
          flymake-languagetool-server-jar))
```

Also documentation needs to be  updated in some way to inform user that 
flymake-languagetool expects languagetool server to be run on port in 
`flymake-languagetool-server-port` and user should adjust 
`flymake-languagetool-server-command` so that it starts command on correct port.

Or we can be just always append "--port" flag to anything user
sets in `flymake-languagetool-server-command`. I think it will work well, since
most distributions should make their wrappers pass additional arguments directly
to server, at least both nixos and arch does this.

**Comment by tpeacock19** [comment]
good catch on the predicate.

The server-port is the default value for languagetool. If a user defines
a custom command and they don't change the port it will work as
expected. However, the docstring should be updated to include its use in
the api url requests. I don't think appending is the right approach.
