### ISSUE TITLE
Disabling backend flymake-languagetool--checker

### ISSUE THREAD

**Issue by genomorro** [emacs-languagetool/flymake-languagetool#8]
Hi, I just installed flymake-languagetool:
```
(use-package flymake-languagetool
  :ensure t
  :hook ((text-mode       . flymake-languagetool-load)
         (latex-mode      . flymake-languagetool-load)
         (org-mode        . flymake-languagetool-load)
         (markdown-mode   . flymake-languagetool-load))
  :init
  (setq flymake-languagetool-server-jar "/opt/LanguageTool-5.7/languagetool-server.jar"))
```
When I open a file and enable flymake-mode, I read in `*Flymake log*` buffer:
```
Warning [flymake mexmiart04t9lab.tex]: Disabling backend flymake-languagetool--checker because (error Autoloading file /usr/share/emacs/27.2/lisp/emacs-lisp/seq.elc failed to define function seq-union)
```
I need a suggestion to solve this. Thanks.

**Comment by tpeacock19** [comment]
Hello, thanks for bringing this to my attention. Can you pull the latest
version from git and let me know if that fixes the issue?

Also, I believe it auto-closed this issue when I referenced it in the
commit message. I do intend to see this fixed of course.

**Comment by genomorro** [comment]
Yes, It's working now. Thanks.
